name: publish nuget package

on:
  push:
    branches:
      - main
      - 'support/**'

env:
  BuildConfiguration: release
  CoreProject: src/Pug.Core/Pug.Core.csproj
  PackagesBaseFolder: packages

jobs:
  build:
    name: Build Projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/PugCS/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build Core project
        run: dotnet build --nologo --configuration ${{env.BuildConfiguration}} ${{env.CoreProject}}

      - name: Create packages base folder
        run: mkdir packages

      - name: Pack Core project
        run: dotnet pack --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.CoreProject}}

      - name: Publish Core NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg